### ISSUE TITLE
[Proposal] Free form writing

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#147]
# Rationale

Having using Sketch extensively for keeping note about everything, I have been thinking about a new writing approach/experience because the current blocks controls sucks.

It's hard to use:
- You have to remember a bunch of shortcuts:
  - Ctrl+Enter: execute the code
  - Shift+Enter: execute and move to next block, if this is last block, create new code block
  - Ctrl+Shift+Enter: same with Shift+Enter but create new text block instead
- As a keyboard user, I find those shortcuts very hard to use/remember
- Hard to reorder blocks, there is an open issue https://github.com/Sketch-sh/sketch-sh/issues/38 but I haven't touch it because it rather complex for implementing drag-and-drop. Also what about code executing orders? 

Developing:
- Complex code: if you've work on Editor_Blocks you know that the block controls logics is very complicated and easy to introduce a bug.
- Hard to add features: undo/redo, real-time collaborations
- Hard to turn a sketch into valid module: I encounter in linking sketches feature. You have to pull some tricks to combine all code blocks into a valid module without introducing syntax errors.  (combines multiple structures into a single structure in at AST level)

# Proposal 

Remove the notion of blocks completely

- There is only a single editor
- All sketches must be a valid RE/ML module

## Writing text

I haven't figured out this part yet, but it should be a comment.

- In OCaml, documentation comment is marked with 2 asterisks 

```
(** ..... *)
```
not sure about ReasonML but we could be the same.

one downside of this approach is that refmt could mess up comment indentation easily.

For details interactions, we can take inspirations from Swift's playground. You can view an introduction of it here: 

https://developer.apple.com/videos/play/wwdc2018/402/ (around ~3:50 minute mark)

I need to keep investigating about this because I don't much how much control CodeMirror gives us to implement such feature.

Please comments/share your ideas below to improve this proposal or even propose a new one.

**Comment by kyldvs** [comment]
How would https://github.com/Sketch-sh/sketch-sh/issues/136 work under this proposal?

**Comment by thangngoc89** [comment]
@kyldvs markdown will be rendered into HTML (as well as everything else) so that shouldn't be an issue

**Comment by no-stack-dub-sack** [comment]
Also, as you said, refmt may be a problem. This would likely drastically affect #137 since from what I've seen, comments get stripped from code when converting from RE to ML (which is quite annoying 💀)

**Comment by kyldvs** [comment]
I feel like this won't actually be simpler, and will make the implementation and how you use the tool more complex. Right now there are "clean" text and code blocks that have clear and separate purposes. There is also the potential to add other kinds of blocks.

"simplifying" into having no kind of blocks and it all being one file will make the mental model of how you think about the document more complex. That is because there are conceptually multiple different kinds of blocks in the notebook, right now that organization is handled for you with discrete blocks in the UI, if that is removed you now have to manually build up your own mental model and groupings within the document.

This also will likely make other potential features (like execution block by block, as in standard notebooks) harder to implement if it becomes all one file and there is no clear notion of a code block. (How could you separate two adjacent code blocks to be distinct execution units?)

If the UX of the current block model is not ideal, we should just try to improve the UX

**Comment by thangngoc89** [comment]
@kyldvs Thank you for your input, considering this a bikeshedding thread. I didn't consider about the mental model. What I have in mind is that single block would make all the hard part of implementing many features goes away. 

As for executing block by block: I don't think that's a good idea. Last Jupyter conf, many folks complaining about unreproducable result be ause of non-deterministic execution order. The current model of Sketch (execution from top to bottom everytime) makes it go away. 

and I agree that UX needs to be improved. 


@no-stack-dub-sack by details I mean how xcode handle special format in the middle of code, as well as embeding video, images easily.

**Comment by kyldvs** [comment]
No problem, just trying to present alternative view points, because I do not seem to mind the blocks that much!

> What I have in mind is that single block would make all the hard part of implementing many features goes away.

Is that still true with a linking/import feature of other notes? Doesn't this act like two blocks being joined together?

Executing block-by-block was just an example of a feature that would be harder, not necessarily one that I'm in support of either. I think there will be others too

I don't know much about the implementation, so perhaps making it one block will greatly simplify implementation, but it doesn't seem ideal for that implementation to leak into the design of the UI. I think the decisions should be mostly independent about which is best. For example, should the internal representation be one large block, and the UI still allow editing in the current "separate" block way?

**Comment by thangngoc89** [comment]
> For example, should the internal representation be one large block, and the UI still allow editing in the current "separate" block way?

That would be the same issue, I'm gonna have to merge the block behind the scene which could lead to unexpected syntax error.

**Comment by Drup** [comment]
Since I emitted the idea that lead to this ticket, let me give my point of view.

The block-based representation works for notebook-like things, like jupyter. These kind of UI works very well for data-science where the text is as important as the code .... and that's it.  Where the code is the central point of focus, like in most other programming tasks, having a single cell that contains both the code, and the text as comment of the code, is much nicer.
As a more general criticism of notebook, you can look at [this presentation](https://docs.google.com/presentation/d/1n2RlMdmv1p25Xy5thJUhkKGvjtV-dkAIsUXP-AL4ffI) (the presentation style is highly obnoxious, but the content is interesting).

There are already notebook tools for OCaml, and nobody uses them. The reason is that most programmers are not interesting in having a notebook-style UI, they want a gist/playground type UI, where you write code, and you comment it with ... actual comments. 

Hence the Idea of having a one-cell document. It has many advantages:
- Reduces the amount of shortcuts to one (and maybe even zero in the future).
- Removes many concepts from the UI, and replaces them with a workflow that is familiar to every programmer: Writing code with comments. This double up for OCaml/Reason programmers, which are used to this notion of documentation comments inside the code. You say this is more "complex". It might be (I disagree) but it doesn't matter: programmers are already used to it, since that's what you do in any text editor.
- Makes the export/import completely trivial and transparent. It's just selecting the text and c/c it.
- Avoid any complications related to the order of evaluation and removes most of the implicit state.
- Open the door to some very nice improvements by leveraging the incremental parsers and automatically figuring out when to rerun the code.

The only downside I see is that it's not a notebook anymore. That's true, but that might not actually be a bad thing.

Of course, we still want to be able to write rich text, that's why (documentation) comments that are closed should be rendered. Apparently according to @thangngoc89 , that's a big tricky to do, but I'm sure he'll figure something. :p

**Comment by Drup** [comment]
> I think this proposal reduces my ability to write these tutorials effectively and I'd move off the platform to something better suited to my needs.

Does it really ? The only different is that you will surround your text by block comments, as if you were writing documentation in code. The rest would work exactly the same: the text would be rendered as it is today (and hopefully better, in the long run).

For most intent and purposes, it just changes `Shift+Enter` into `/*`. :)
Except now, reordering is trivial since everything is text, and undo/redo might have a chance to be implementable!

**Comment by no-stack-dub-sack** [comment]
@thangngoc89 What about "tabs" instead of blocks? This implements the single-cell model, potentially eliminating some implementation challenges, but still allows for a kind of "block model," where each piece of code is easily accessible and easy to reason about and mentally compartmentalize. This might solve a few of these problems. Each "tab" would have to be a valid RE/ML module, would allow for undo, and could have text rendered from comments off to the side. Yet for use cases like @kyldvs's, you could still have very nice organization for these kinds of tutorials. Maybe even better, because it could introduce a sort of pagination, instead of very long scrolls like in your third example. 

If HTML rendered from comments is hard to do due to CodePen's limitations, you could have the ability to add comment bubbles or blocks that integrate nicely into the single-file off to the right or left. OR, maybe allow just a single text block above a single code block.

This is a very loose picture of how this might work/look, but it might represent a happy medium between these two ideas that could solve some of the implementation challenges in how code blocks are represented / executed. This is almost like taking today's platform and flipping it sideways, except the code blocks would no longer be connected.

**Comment by Drup** [comment]
@kyldvs I didn't say the different was slight, I said your workflow can be trivially maintained with a single-cell UI. ;)
Do you have concrete desirable features that would be easier to implement with a block UI ?

@no-stack-dub-sack I like it. Another interesting aspects of having tabs (which is really just a way to group sketches together, in a way) is that it naturally provides a way to group an implementation and its interface together. I would leave that for latter though.

**Comment by thangngoc89** [comment]
Thank you all for your thoughts. I can see that there are 2 directions here:

- @no-stack-dub-sack @Drup : A full-blow playground. That tab ideas is basically an IDE. (a file explorer, a tab manager in the top)
- @kyldvs keep the current UI.

And both have valid feedbacks. and both have their use cases. 
Now that linking sketches is in the work, I think that I can unite both use cases. You have a file explorer to store preparations files. And a notebook interface (current one) to represent your ideas. 

I came to this conclusions because it's **possible** to render comment whenever you closed it (like what @Drup suggested) . But it's extremely hard to do and has poor performances (that's definitely not what CodeMirror was build for)

And I myself like having blocks. It's easier to write and demonstrate my ideas.

**Comment by matthiaskern** [comment]
I like the current single file model, and think if we get the concept of linking right, there might not be a need for a full blown file explorer and IDE capabilities. For this use case, there are other services like repl.it as well as codesandbox which apparently has reason support on the horizon.

I agree that we need to simplify the editor model, I still get confused by the current shortcuts, perhaps because I 've never really used jupyter notebooks before.
Short-term a shortcut to comment code, and an export functionality that would simply serialize text blocks to comment statements could be of use.
Longer-term we could investigate if there are other editor options that would give use better rendering capabilities and enable us to head more in the direction of the single block model.

**Comment by no-stack-dub-sack** [comment]
@matthiaskern ctrl+/ should comment code

**Comment by thangngoc89** [comment]
@no-stack-dub-sack @matthiaskern implemented the comment code shortcut ;) I would a PR to change that to mod (not sure how this work with codemirror though)

**Comment by no-stack-dub-sack** [comment]
@thangngoc89 sure, I can submit a quick PR for this. It should be simple as setting an editor config for both keys since I don't think CodeMirror recognizes mod, but I can check (so both ctrl and cmd would work on PC, which might be helpful if mac users have gotten accustomed to using ctrl)

**Comment by matthiaskern** [comment]
investigating https://www.slatejs.org/ and https://prosemirror.net/
