### ISSUE TITLE
Confirmation before deleting a block

### ISSUE THREAD

**Issue by thangngoc89** [Sketch-sh/sketch-sh#15]
Currently, it's too easy to delete a block, a little confirmation would be nice. And no confirmation needed for empty block

**Comment by thangngoc89** [comment]
@alireza-a my idea is show a confirmation modal when you click delete. not sire what do you mean by replacing delete-button with confirm-button

**Comment by thangngoc89** [comment]
@alireza-a @kyldvs  Thank you for the explanation. indeed replacing delete button with confirm button is better UX. But I like @kyldvs more. like add opacity = 50 to deleted block. count down to 10 or next edit before actually deleted it. of course, give user something to restore the block or delete it immediately (the delete immediately button should be hard to reach)

**Comment by kyldvs** [comment]
All of these sound good to me! I think if you go with the fake block I would actually not display the content, otherwise for large blocks it can look weird. I would replace it with a fake block that always says the same thing and is easy to recognize. Perhaps a yellow warning-like block that says, "This block has been deleted, to restore the content click undo." and has an undo button on the right side.

**Comment by thangngoc89** [comment]
@kyldvs sound good to me

**Comment by no-stack-dub-sack** [comment]
I'd be interested in giving this a try, but not sure I'll have time until sometime next week. I'll leave another comment when I start this, but if someone else comes along in the meantime and I still haven't started yet, please feel free to go ahead

**Comment by no-stack-dub-sack** [comment]
Working on this now... going away for a few days with no internet but will resume when I return if not too urgent

**Comment by thangngoc89** [comment]
@no-stack-dub-sack thank you for working on this. this is not that urgent so no worries
